### ISSUE TITLE
About the code running can not get the result

### ISSUE THREAD

**Issue by Tianzh3n** [D1noFuzi/cmd_styletransfer#4]
Hi, I am very interested in your article. But when I run the code according to the prompt you gave, the pictures that need to be updated cannot be updated. The loss obtained in the first iteration is the same as the second, resulting in a Delta smaller than eps, why is this?
![image](https://user-images.githubusercontent.com/73298343/163227537-f7083fff-c56f-4bff-ac1e-1fe10b80bd27.png)

**Comment by D1noFuzi** [comment]
Hi, 
that is tough to say just from what you wrote. But I would go ahead and try to take a super small epsilon and see if your images are getting updated.
